export {default as Logo} from './header/logo.svg';
export {default as searchIcon} from './header/search.svg';
export {default as cartIcon} from './header/cart.svg';
export {default as profileIcon} from './header/profile.svg';
export {default as sepLine} from './header/line.svg';
export {default as mediaIcons } from './footer/SocialMedia.svg';
export {default as arrowIcon} from './shop/arrow.svg';
export {default as fillStar} from './productPage/fill_star.svg';
export {default as Star} from './productPage/star.svg';
export {default as Wishlist} from './productPage/Wishlist.svg';